require'orbsa.plugins._treesitter'
require'orbsa.plugins._copilot'
require'orbsa.plugins._navigator'
require'orbsa.plugins._lualine'
require'orbsa.plugins._flash'
require'orbsa.plugins._telescope'
require'orbsa.plugins._harpoon'
require'orbsa.plugins._typescript-tools'
require'orbsa.plugins._todo-comments'
require'orbsa.plugins._dap'
require'orbsa.plugins._dropbar'
-- require'orbsa.plugins._smear'
-- require'orbsa.plugins._neoscroll'
require'orbsa.plugins._rust'
require'orbsa.plugins._git'
require'orbsa.plugins._oil'
require'orbsa.plugins._lsp'
require'orbsa.plugins._nvim-cmp'
require'orbsa.plugins._zen'
